//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADCP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADCP.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于....
        /// </summary>
        internal static string str_About {
            get {
                return ResourceManager.GetString("str_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 泛际测流大师软件 V4.0  2013-05.
        /// </summary>
        internal static string str_aboutText1 {
            get {
                return ResourceManager.GetString("str_aboutText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版权(C)2013-2018 上海泛际科学仪器有限公司.
        /// </summary>
        internal static string str_aboutText2 {
            get {
                return ResourceManager.GetString("str_aboutText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海泛际科学仪器有限公司(Pan-Comm)是一家集研究开发、生产、销售及客户服务的高科技海洋仪器专业公司。公司集电子信息、计算机软件、仪器仪表等高端技术产业于一身，是“三高一无”科技企业。Pan-Comm并与国内外多家科研单位，高等院校和世界一流海洋仪器生产厂商合作，共同努力发展我国的海洋开发事业。.
        /// </summary>
        internal static string str_aboutText3 {
            get {
                return ResourceManager.GetString("str_aboutText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地址：上海市漕河泾开发区松江高科园莘砖公路518弄11号楼701室.
        /// </summary>
        internal static string str_aboutText4 {
            get {
                return ResourceManager.GetString("str_aboutText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版权所有。.
        /// </summary>
        internal static string str_aboutText5 {
            get {
                return ResourceManager.GetString("str_aboutText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! 线程已断，无法接受GPS数据。.
        /// </summary>
        internal static string str_errorGPS {
            get {
                return ResourceManager.GetString("str_errorGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助....
        /// </summary>
        internal static string str_Help {
            get {
                return ResourceManager.GetString("str_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请参看 《RTI ADCP/DVL 用户手册》 及 .
        /// </summary>
        internal static string str_HelpText1 {
            get {
                return ResourceManager.GetString("str_HelpText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 《测流大师（DP-Pro）软件应用指南》.
        /// </summary>
        internal static string str_HelpText2 {
            get {
                return ResourceManager.GetString("str_HelpText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示：DVL 测量：.
        /// </summary>
        internal static string str_noteDVL1 {
            get {
                return ResourceManager.GetString("str_noteDVL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您没有该功能的使用权限！.
        /// </summary>
        internal static string str_noteDVL2 {
            get {
                return ResourceManager.GetString("str_noteDVL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示：您没有该功能的使用权限！.
        /// </summary>
        internal static string str_noteRight1 {
            get {
                return ResourceManager.GetString("str_noteRight1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请联系上海泛际科学仪器有限公司.
        /// </summary>
        internal static string str_noteRight2 {
            get {
                return ResourceManager.GetString("str_noteRight2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示：波浪测量：.
        /// </summary>
        internal static string str_noteWave1 {
            get {
                return ResourceManager.GetString("str_noteWave1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电话： +86 21 34060911.
        /// </summary>
        internal static string str_Tel {
            get {
                return ResourceManager.GetString("str_Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效结果:.
        /// </summary>
        internal static string str_unuse1 {
            get {
                return ResourceManager.GetString("str_unuse1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有效结果:.
        /// </summary>
        internal static string str_use1 {
            get {
                return ResourceManager.GetString("str_use1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顶部流量:.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通讯口名称不能为空.
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 船速.
        /// </summary>
        internal static string String100 {
            get {
                return ResourceManager.GetString("String100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 船向.
        /// </summary>
        internal static string String101 {
            get {
                return ResourceManager.GetString("String101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流速.
        /// </summary>
        internal static string String102 {
            get {
                return ResourceManager.GetString("String102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流向.
        /// </summary>
        internal static string String103 {
            get {
                return ResourceManager.GetString("String103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 航迹长度.
        /// </summary>
        internal static string String104 {
            get {
                return ResourceManager.GetString("String104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 直线距离.
        /// </summary>
        internal static string String105 {
            get {
                return ResourceManager.GetString("String105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 直线方向.
        /// </summary>
        internal static string String106 {
            get {
                return ResourceManager.GetString("String106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 河宽.
        /// </summary>
        internal static string String107 {
            get {
                return ResourceManager.GetString("String107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总面积.
        /// </summary>
        internal static string String108 {
            get {
                return ResourceManager.GetString("String108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均流速.
        /// </summary>
        internal static string String109 {
            get {
                return ResourceManager.GetString("String109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 串口配置不正确！.
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均流向.
        /// </summary>
        internal static string String110 {
            get {
                return ResourceManager.GetString("String110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他信息.
        /// </summary>
        internal static string String111 {
            get {
                return ResourceManager.GetString("String111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时间.
        /// </summary>
        internal static string String112 {
            get {
                return ResourceManager.GetString("String112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测量时间.
        /// </summary>
        internal static string String113 {
            get {
                return ResourceManager.GetString("String113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测量总数.
        /// </summary>
        internal static string String114 {
            get {
                return ResourceManager.GetString("String114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前水深.
        /// </summary>
        internal static string String115 {
            get {
                return ResourceManager.GetString("String115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 经度.
        /// </summary>
        internal static string String116 {
            get {
                return ResourceManager.GetString("String116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纬度.
        /// </summary>
        internal static string String117 {
            get {
                return ResourceManager.GetString("String117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艏向.
        /// </summary>
        internal static string String118 {
            get {
                return ResourceManager.GetString("String118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纵倾.
        /// </summary>
        internal static string String119 {
            get {
                return ResourceManager.GetString("String119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS罗经串口配置不正确！.
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 横摇.
        /// </summary>
        internal static string String120 {
            get {
                return ResourceManager.GetString("String120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 真北.
        /// </summary>
        internal static string String121 {
            get {
                return ResourceManager.GetString("String121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部显示.
        /// </summary>
        internal static string String122 {
            get {
                return ResourceManager.GetString("String122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部分显示/.
        /// </summary>
        internal static string String123 {
            get {
                return ResourceManager.GetString("String123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浅水.
        /// </summary>
        internal static string String124 {
            get {
                return ResourceManager.GetString("String124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一般.
        /// </summary>
        internal static string String125 {
            get {
                return ResourceManager.GetString("String125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深水.
        /// </summary>
        internal static string String126 {
            get {
                return ResourceManager.GetString("String126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 专家模式.
        /// </summary>
        internal static string String127 {
            get {
                return ResourceManager.GetString("String127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户模式.
        /// </summary>
        internal static string String128 {
            get {
                return ResourceManager.GetString("String128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 层数.
        /// </summary>
        internal static string String129 {
            get {
                return ResourceManager.GetString("String129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 串口冲突，请重设！.
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先确保已安装Microsoft Office Excel 2007或以上版本！.
        /// </summary>
        internal static string String130 {
            get {
                return ResourceManager.GetString("String130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先输入测站基本信息！.
        /// </summary>
        internal static string String131 {
            get {
                return ResourceManager.GetString("String131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表B-.
        /// </summary>
        internal static string String132 {
            get {
                return ResourceManager.GetString("String132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 站声学多普勒流速仪测量测验记载表.
        /// </summary>
        internal static string String133 {
            get {
                return ResourceManager.GetString("String133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日期:.
        /// </summary>
        internal static string String134 {
            get {
                return ResourceManager.GetString("String134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年.
        /// </summary>
        internal static string String135 {
            get {
                return ResourceManager.GetString("String135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月.
        /// </summary>
        internal static string String136 {
            get {
                return ResourceManager.GetString("String136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日.
        /// </summary>
        internal static string String137 {
            get {
                return ResourceManager.GetString("String137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天气：.
        /// </summary>
        internal static string String138 {
            get {
                return ResourceManager.GetString("String138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 风力风向：.
        /// </summary>
        internal static string String139 {
            get {
                return ResourceManager.GetString("String139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示：下一步请选择《测流控制》页，然后依次选择“连接仪器”和“开始测量”。.
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测量测次：.
        /// </summary>
        internal static string String140 {
            get {
                return ResourceManager.GetString("String140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测船：.
        /// </summary>
        internal static string String141 {
            get {
                return ResourceManager.GetString("String141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计算机名：.
        /// </summary>
        internal static string String142 {
            get {
                return ResourceManager.GetString("String142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始时间：.
        /// </summary>
        internal static string String143 {
            get {
                return ResourceManager.GetString("String143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束时间：.
        /// </summary>
        internal static string String144 {
            get {
                return ResourceManager.GetString("String144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均时间：.
        /// </summary>
        internal static string String145 {
            get {
                return ResourceManager.GetString("String145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测速仪型号：.
        /// </summary>
        internal static string String146 {
            get {
                return ResourceManager.GetString("String146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 固件版本：.
        /// </summary>
        internal static string String147 {
            get {
                return ResourceManager.GetString("String147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软件版本：.
        /// </summary>
        internal static string String148 {
            get {
                return ResourceManager.GetString("String148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据文件路径：.
        /// </summary>
        internal static string String149 {
            get {
                return ResourceManager.GetString("String149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目前处于回放模式，请先切换至跟踪显示模式，再配置！.
        /// </summary>
        internal static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置文件名称：Config.cfg.
        /// </summary>
        internal static string String150 {
            get {
                return ResourceManager.GetString("String150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS型号：.
        /// </summary>
        internal static string String151 {
            get {
                return ResourceManager.GetString("String151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 罗经型号：.
        /// </summary>
        internal static string String152 {
            get {
                return ResourceManager.GetString("String152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测深仪型号：.
        /// </summary>
        internal static string String153 {
            get {
                return ResourceManager.GetString("String153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 探头入水深:.
        /// </summary>
        internal static string String154 {
            get {
                return ResourceManager.GetString("String154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置的盲区：.
        /// </summary>
        internal static string String155 {
            get {
                return ResourceManager.GetString("String155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深度单元尺寸:.
        /// </summary>
        internal static string String156 {
            get {
                return ResourceManager.GetString("String156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深度单元数：.
        /// </summary>
        internal static string String157 {
            get {
                return ResourceManager.GetString("String157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 含盐度：.
        /// </summary>
        internal static string String158 {
            get {
                return ResourceManager.GetString("String158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水跟踪脉冲数：.
        /// </summary>
        internal static string String159 {
            get {
                return ResourceManager.GetString("String159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 串口通讯出现故障！.
        /// </summary>
        internal static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 底跟踪脉冲数：.
        /// </summary>
        internal static string String160 {
            get {
                return ResourceManager.GetString("String160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幂指数b:.
        /// </summary>
        internal static string String161 {
            get {
                return ResourceManager.GetString("String161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测回.
        /// </summary>
        internal static string String162 {
            get {
                return ResourceManager.GetString("String162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 航向.
        /// </summary>
        internal static string String163 {
            get {
                return ResourceManager.GetString("String163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水边距离.
        /// </summary>
        internal static string String164 {
            get {
                return ResourceManager.GetString("String164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据文件名.
        /// </summary>
        internal static string String165 {
            get {
                return ResourceManager.GetString("String165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 半测回流量.
        /// </summary>
        internal static string String166 {
            get {
                return ResourceManager.GetString("String166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测回平均流量.
        /// </summary>
        internal static string String167 {
            get {
                return ResourceManager.GetString("String167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备注.
        /// </summary>
        internal static string String168 {
            get {
                return ResourceManager.GetString("String168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右岸-左岸.
        /// </summary>
        internal static string String169 {
            get {
                return ResourceManager.GetString("String169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先连接串口！.
        /// </summary>
        internal static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左岸-右岸.
        /// </summary>
        internal static string String170 {
            get {
                return ResourceManager.GetString("String170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测    验    结    果.
        /// </summary>
        internal static string String171 {
            get {
                return ResourceManager.GetString("String171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测验项目.
        /// </summary>
        internal static string String172 {
            get {
                return ResourceManager.GetString("String172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测回.
        /// </summary>
        internal static string String173 {
            get {
                return ResourceManager.GetString("String173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测次平均.
        /// </summary>
        internal static string String174 {
            get {
                return ResourceManager.GetString("String174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 往测.
        /// </summary>
        internal static string String175 {
            get {
                return ResourceManager.GetString("String175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返测.
        /// </summary>
        internal static string String176 {
            get {
                return ResourceManager.GetString("String176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 断面流量.
        /// </summary>
        internal static string String177 {
            get {
                return ResourceManager.GetString("String177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 断面面积.
        /// </summary>
        internal static string String178 {
            get {
                return ResourceManager.GetString("String178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均流速.
        /// </summary>
        internal static string String179 {
            get {
                return ResourceManager.GetString("String179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统正在进行工程测量，是否要保存工程文件？.
        /// </summary>
        internal static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大流速.
        /// </summary>
        internal static string String180 {
            get {
                return ResourceManager.GetString("String180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均水深.
        /// </summary>
        internal static string String181 {
            get {
                return ResourceManager.GetString("String181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大水深.
        /// </summary>
        internal static string String182 {
            get {
                return ResourceManager.GetString("String182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水面宽.
        /// </summary>
        internal static string String183 {
            get {
                return ResourceManager.GetString("String183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始水位：.
        /// </summary>
        internal static string String184 {
            get {
                return ResourceManager.GetString("String184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束水位：.
        /// </summary>
        internal static string String185 {
            get {
                return ResourceManager.GetString("String185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均水位：.
        /// </summary>
        internal static string String186 {
            get {
                return ResourceManager.GetString("String186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相应水位：.
        /// </summary>
        internal static string String187 {
            get {
                return ResourceManager.GetString("String187", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作记录：.
        /// </summary>
        internal static string String188 {
            get {
                return ResourceManager.GetString("String188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 现场审查：.
        /// </summary>
        internal static string String189 {
            get {
                return ResourceManager.GetString("String189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        internal static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 审定：.
        /// </summary>
        internal static string String190 {
            get {
                return ResourceManager.GetString("String190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 楷体.
        /// </summary>
        internal static string String191 {
            get {
                return ResourceManager.GetString("String191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存:.
        /// </summary>
        internal static string String192 {
            get {
                return ResourceManager.GetString("String192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户模式：建议一般用户使用！.
        /// </summary>
        internal static string String193 {
            get {
                return ResourceManager.GetString("String193", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 专家模式：根据详细的命令设置配置！.
        /// </summary>
        internal static string String194 {
            get {
                return ResourceManager.GetString("String194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当底跟踪的信噪比小于设置的门限值时，认为该值不好。默认门限值浅水为15，深水为5.
        /// </summary>
        internal static string String195 {
            get {
                return ResourceManager.GetString("String195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当底跟踪的相关性值小于设置的门限值时，认为该值不好，且该值不用于计算平均值。默认门限值为0.9.
        /// </summary>
        internal static string String196 {
            get {
                return ResourceManager.GetString("String196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当水剖面的相关性小于设置的门限值是，认为该值不好，且该值不用于bin平均。默认门限值为0.4.
        /// </summary>
        internal static string String197 {
            get {
                return ResourceManager.GetString("String197", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测流地理坐标良好率是指在该单元层中的发射的呯数与实际可用的呯数的比值.
        /// </summary>
        internal static string String198 {
            get {
                return ResourceManager.GetString("String198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测流波束坐标良好率.
        /// </summary>
        internal static string String199 {
            get {
                return ResourceManager.GetString("String199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 底部流量:.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作失败，回放所必需的文件丢失！.
        /// </summary>
        internal static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地球坐标系下的流速.
        /// </summary>
        internal static string String200 {
            get {
                return ResourceManager.GetString("String200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仪器坐标系下的流速.
        /// </summary>
        internal static string String201 {
            get {
                return ResourceManager.GetString("String201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 波束方向上的流速.
        /// </summary>
        internal static string String202 {
            get {
                return ResourceManager.GetString("String202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地球坐标系下的底跟踪速度.
        /// </summary>
        internal static string String203 {
            get {
                return ResourceManager.GetString("String203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仪器坐标系下的底跟踪速度.
        /// </summary>
        internal static string String204 {
            get {
                return ResourceManager.GetString("String204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 波束方向的底跟踪速度.
        /// </summary>
        internal static string String205 {
            get {
                return ResourceManager.GetString("String205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地球坐标系的水剖面ping的良好率.
        /// </summary>
        internal static string String206 {
            get {
                return ResourceManager.GetString("String206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 波束方向上的水剖面ping的良好率.
        /// </summary>
        internal static string String207 {
            get {
                return ResourceManager.GetString("String207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地球坐标系下的底跟踪ping的良好率.
        /// </summary>
        internal static string String208 {
            get {
                return ResourceManager.GetString("String208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仪器坐标系下的底跟踪ping的良好率.
        /// </summary>
        internal static string String209 {
            get {
                return ResourceManager.GetString("String209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工程名：.
        /// </summary>
        internal static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 波束方向上的底跟踪ping的良好率.
        /// </summary>
        internal static string String210 {
            get {
                return ResourceManager.GetString("String210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水剖面相关性，默认的相关性阈值为0.4。当某个单元层的相关性值小于设定的阈值，则认为该数据不可用，予以剔除。.
        /// </summary>
        internal static string String211 {
            get {
                return ResourceManager.GetString("String211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 底跟踪相关性，默认的底跟踪相关性阈值为0.9。当某一ping的相关性小于设定的阈值，则认为该数据不可用，予以剔除。.
        /// </summary>
        internal static string String212 {
            get {
                return ResourceManager.GetString("String212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水剖面回波强度.
        /// </summary>
        internal static string String213 {
            get {
                return ResourceManager.GetString("String213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 底跟踪回波强度.
        /// </summary>
        internal static string String214 {
            get {
                return ResourceManager.GetString("String214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (m/s).
        /// </summary>
        internal static string String215 {
            get {
                return ResourceManager.GetString("String215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (度).
        /// </summary>
        internal static string String216 {
            get {
                return ResourceManager.GetString("String216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该页面用于配置流量测量参数。.
        /// </summary>
        internal static string String217 {
            get {
                return ResourceManager.GetString("String217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当用户设置完成所有配置参数后，请点击工具栏上的“开始”按钮（或点击快捷键“F5”），启动流量测量。.
        /// </summary>
        internal static string String218 {
            get {
                return ResourceManager.GetString("String218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户可根据实际情况修改流量测量参数。.
        /// </summary>
        internal static string String219 {
            get {
                return ResourceManager.GetString("String219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建时间：.
        /// </summary>
        internal static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流速剖面图 - 参考:.
        /// </summary>
        internal static string String220 {
            get {
                return ResourceManager.GetString("String220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 三角形 (斜坡).
        /// </summary>
        internal static string String221 {
            get {
                return ResourceManager.GetString("String221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 矩形 (垂直).
        /// </summary>
        internal static string String222 {
            get {
                return ResourceManager.GetString("String222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义.
        /// </summary>
        internal static string String223 {
            get {
                return ResourceManager.GetString("String223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 常数.
        /// </summary>
        internal static string String224 {
            get {
                return ResourceManager.GetString("String224", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 三点外延.
        /// </summary>
        internal static string String225 {
            get {
                return ResourceManager.GetString("String225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左岸.
        /// </summary>
        internal static string String226 {
            get {
                return ResourceManager.GetString("String226", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右岸.
        /// </summary>
        internal static string String227 {
            get {
                return ResourceManager.GetString("String227", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软件计算.
        /// </summary>
        internal static string String228 {
            get {
                return ResourceManager.GetString("String228", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仪器获取.
        /// </summary>
        internal static string String229 {
            get {
                return ResourceManager.GetString("String229", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件路径：.
        /// </summary>
        internal static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内置罗盘.
        /// </summary>
        internal static string String230 {
            get {
                return ResourceManager.GetString("String230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外接罗盘.
        /// </summary>
        internal static string String231 {
            get {
                return ResourceManager.GetString("String231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 底跟踪.
        /// </summary>
        internal static string String232 {
            get {
                return ResourceManager.GetString("String232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无参考.
        /// </summary>
        internal static string String233 {
            get {
                return ResourceManager.GetString("String233", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户模式.
        /// </summary>
        internal static string String234 {
            get {
                return ResourceManager.GetString("String234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 专家模式.
        /// </summary>
        internal static string String235 {
            get {
                return ResourceManager.GetString("String235", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公制.
        /// </summary>
        internal static string String236 {
            get {
                return ResourceManager.GetString("String236", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 英制.
        /// </summary>
        internal static string String237 {
            get {
                return ResourceManager.GetString("String237", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水深.
        /// </summary>
        internal static string String238 {
            get {
                return ResourceManager.GetString("String238", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测量.
        /// </summary>
        internal static string String239 {
            get {
                return ResourceManager.GetString("String239", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否放弃当前回放，开始新的项目回放？.
        /// </summary>
        internal static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回放.
        /// </summary>
        internal static string String240 {
            get {
                return ResourceManager.GetString("String240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        internal static string String241 {
            get {
                return ResourceManager.GetString("String241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        internal static string String242 {
            get {
                return ResourceManager.GetString("String242", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 美国亚奇科技公司.
        /// </summary>
        internal static string String243 {
            get {
                return ResourceManager.GetString("String243", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海泛际科学仪器有限公司.
        /// </summary>
        internal static string String244 {
            get {
                return ResourceManager.GetString("String244", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该程序正在运行，请勿重复运行！.
        /// </summary>
        internal static string String245 {
            get {
                return ResourceManager.GetString("String245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户手册.
        /// </summary>
        internal static string String246 {
            get {
                return ResourceManager.GetString("String246", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTI网站.
        /// </summary>
        internal static string String247 {
            get {
                return ResourceManager.GetString("String247", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 泛际网站.
        /// </summary>
        internal static string String248 {
            get {
                return ResourceManager.GetString("String248", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 泛际测流大师软件.
        /// </summary>
        internal static string String249 {
            get {
                return ResourceManager.GetString("String249", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法打开原始数据，请检查原始数据文件是否有效！.
        /// </summary>
        internal static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本:.
        /// </summary>
        internal static string String250 {
            get {
                return ResourceManager.GetString("String250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海泛际科学仪器有限公司.
        /// </summary>
        internal static string String251 {
            get {
                return ResourceManager.GetString("String251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版权所有@.
        /// </summary>
        internal static string String252 {
            get {
                return ResourceManager.GetString("String252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均值.
        /// </summary>
        internal static string String253 {
            get {
                return ResourceManager.GetString("String253", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标准差.
        /// </summary>
        internal static string String254 {
            get {
                return ResourceManager.GetString("String254", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 误差.
        /// </summary>
        internal static string String255 {
            get {
                return ResourceManager.GetString("String255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始岸边测量，请点击这里！（或按快捷键“F5”）.
        /// </summary>
        internal static string String256 {
            get {
                return ResourceManager.GetString("String256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始走航测量，请点击这里！（或按快捷键“F5”）.
        /// </summary>
        internal static string String257 {
            get {
                return ResourceManager.GetString("String257", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始发射呯，请点击这里！（或按快捷键“F5”）.
        /// </summary>
        internal static string String258 {
            get {
                return ResourceManager.GetString("String258", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止发射呯，请点击这里！（或按快捷键“F6”）.
        /// </summary>
        internal static string String259 {
            get {
                return ResourceManager.GetString("String259", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 载入回放数据错误，请检查文件格式是否正确！.
        /// </summary>
        internal static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件名.
        /// </summary>
        internal static string String260 {
            get {
                return ResourceManager.GetString("String260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 起始日期.
        /// </summary>
        internal static string String261 {
            get {
                return ResourceManager.GetString("String261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 起始时间.
        /// </summary>
        internal static string String262 {
            get {
                return ResourceManager.GetString("String262", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在发射呯.
        /// </summary>
        internal static string String263 {
            get {
                return ResourceManager.GetString("String263", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在测量起始岸.
        /// </summary>
        internal static string String264 {
            get {
                return ResourceManager.GetString("String264", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在走航.
        /// </summary>
        internal static string String265 {
            get {
                return ResourceManager.GetString("String265", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在测量结束岸.
        /// </summary>
        internal static string String266 {
            get {
                return ResourceManager.GetString("String266", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止发射呯.
        /// </summary>
        internal static string String267 {
            get {
                return ResourceManager.GetString("String267", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据组号.
        /// </summary>
        internal static string String268 {
            get {
                return ResourceManager.GetString("String268", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日期.
        /// </summary>
        internal static string String269 {
            get {
                return ResourceManager.GetString("String269", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回放文件终端，请退出或改变回放起点。.
        /// </summary>
        internal static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (度).
        /// </summary>
        internal static string String270 {
            get {
                return ResourceManager.GetString("String270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 船速/流速.
        /// </summary>
        internal static string String271 {
            get {
                return ResourceManager.GetString("String271", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 航迹距离.
        /// </summary>
        internal static string String272 {
            get {
                return ResourceManager.GetString("String272", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一个.
        /// </summary>
        internal static string String273 {
            get {
                return ResourceManager.GetString("String273", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示汇总信息.
        /// </summary>
        internal static string String274 {
            get {
                return ResourceManager.GetString("String274", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主页.
        /// </summary>
        internal static string String275 {
            get {
                return ResourceManager.GetString("String275", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        internal static string String276 {
            get {
                return ResourceManager.GetString("String276", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始测量.
        /// </summary>
        internal static string String277 {
            get {
                return ResourceManager.GetString("String277", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始岸边.
        /// </summary>
        internal static string String278 {
            get {
                return ResourceManager.GetString("String278", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 走航.
        /// </summary>
        internal static string String279 {
            get {
                return ResourceManager.GetString("String279", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尚未创建工程... ....
        /// </summary>
        internal static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束岸边.
        /// </summary>
        internal static string String280 {
            get {
                return ResourceManager.GetString("String280", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束测量.
        /// </summary>
        internal static string String281 {
            get {
                return ResourceManager.GetString("String281", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        internal static string String282 {
            get {
                return ResourceManager.GetString("String282", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先查看测量模式(第四步：系统设置)！.
        /// </summary>
        internal static string String283 {
            get {
                return ResourceManager.GetString("String283", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上海泛际.
        /// </summary>
        internal static string String284 {
            get {
                return ResourceManager.GetString("String284", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到下一个可读文件！.
        /// </summary>
        internal static string String285 {
            get {
                return ResourceManager.GetString("String285", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 串口被占用.
        /// </summary>
        internal static string String286 {
            get {
                return ResourceManager.GetString("String286", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 极浅水.
        /// </summary>
        internal static string String287 {
            get {
                return ResourceManager.GetString("String287", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统罗盘未工作。.
        /// </summary>
        internal static string String288 {
            get {
                return ResourceManager.GetString("String288", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总大小：.
        /// </summary>
        internal static string String289 {
            get {
                return ResourceManager.GetString("String289", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未接受任何数据... ....
        /// </summary>
        internal static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已用空间：.
        /// </summary>
        internal static string String290 {
            get {
                return ResourceManager.GetString("String290", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到SD卡。.
        /// </summary>
        internal static string String291 {
            get {
                return ResourceManager.GetString("String291", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统电量为：.
        /// </summary>
        internal static string String292 {
            get {
                return ResourceManager.GetString("String292", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水温为：.
        /// </summary>
        internal static string String293 {
            get {
                return ResourceManager.GetString("String293", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未检测到温度传感器。.
        /// </summary>
        internal static string String294 {
            get {
                return ResourceManager.GetString("String294", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统测试.
        /// </summary>
        internal static string String295 {
            get {
                return ResourceManager.GetString("String295", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通讯故障.
        /// </summary>
        internal static string String296 {
            get {
                return ResourceManager.GetString("String296", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请检查ADCP通讯线路或电源供电是否正常.
        /// </summary>
        internal static string String297 {
            get {
                return ResourceManager.GetString("String297", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请检查GPS通讯线路或电源供电是否正常.
        /// </summary>
        internal static string String298 {
            get {
                return ResourceManager.GetString("String298", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在下载....
        /// </summary>
        internal static string String299 {
            get {
                return ResourceManager.GetString("String299", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实测流量:.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无GPS数据... ....
        /// </summary>
        internal static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载完成.
        /// </summary>
        internal static string String300 {
            get {
                return ResourceManager.GetString("String300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载失败.
        /// </summary>
        internal static string String301 {
            get {
                return ResourceManager.GetString("String301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送DSDIR命令失败.
        /// </summary>
        internal static string String302 {
            get {
                return ResourceManager.GetString("String302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网址：.
        /// </summary>
        internal static string String303 {
            get {
                return ResourceManager.GetString("String303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法找到软件狗！.
        /// </summary>
        internal static string String304 {
            get {
                return ResourceManager.GetString("String304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 采用默认配置.
        /// </summary>
        internal static string String305 {
            get {
                return ResourceManager.GetString("String305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始数据采集，请点击这里！（或按快捷键“F5”）.
        /// </summary>
        internal static string String306 {
            get {
                return ResourceManager.GetString("String306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止数据采集，请点击这里！（或按快捷键“F6”）.
        /// </summary>
        internal static string String307 {
            get {
                return ResourceManager.GetString("String307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在数据采集.
        /// </summary>
        internal static string String308 {
            get {
                return ResourceManager.GetString("String308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止数据采集.
        /// </summary>
        internal static string String309 {
            get {
                return ResourceManager.GetString("String309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接仪器.
        /// </summary>
        internal static string String31 {
            get {
                return ResourceManager.GetString("String31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流量报表输出完成！.
        /// </summary>
        internal static string String310 {
            get {
                return ResourceManager.GetString("String310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流量报表输出失败！.
        /// </summary>
        internal static string String311 {
            get {
                return ResourceManager.GetString("String311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流量报表输出失败，缺少流量数据！.
        /// </summary>
        internal static string String312 {
            get {
                return ResourceManager.GetString("String312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 航迹图.
        /// </summary>
        internal static string String313 {
            get {
                return ResourceManager.GetString("String313", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 船速参考.
        /// </summary>
        internal static string String314 {
            get {
                return ResourceManager.GetString("String314", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始发射.
        /// </summary>
        internal static string String32 {
            get {
                return ResourceManager.GetString("String32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 幂函数.
        /// </summary>
        internal static string String33 {
            get {
                return ResourceManager.GetString("String33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 三角形.
        /// </summary>
        internal static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统正在进行工程回放，是否要结束回放？.
        /// </summary>
        internal static string String35 {
            get {
                return ResourceManager.GetString("String35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要退出测量？.
        /// </summary>
        internal static string String36 {
            get {
                return ResourceManager.GetString("String36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选用GPS罗经时必须同时选定GPS！.
        /// </summary>
        internal static string String37 {
            get {
                return ResourceManager.GetString("String37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改失败，输入配置参数据有误，请检查！.
        /// </summary>
        internal static string String38 {
            get {
                return ResourceManager.GetString("String38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置文件丢失，请重新选择。.
        /// </summary>
        internal static string String39 {
            get {
                return ResourceManager.GetString("String39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 岸边流量:.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 断开仪器.
        /// </summary>
        internal static string String40 {
            get {
                return ResourceManager.GetString("String40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有创建工程，请先点击“新建工程”按钮以创建系的工程。.
        /// </summary>
        internal static string String41 {
            get {
                return ResourceManager.GetString("String41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS连接失败！.
        /// </summary>
        internal static string String42 {
            get {
                return ResourceManager.GetString("String42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在接受数据... ....
        /// </summary>
        internal static string String43 {
            get {
                return ResourceManager.GetString("String43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂停发射.
        /// </summary>
        internal static string String44 {
            get {
                return ResourceManager.GetString("String44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 串口通讯出现故障,无法连接仪器串口！.
        /// </summary>
        internal static string String45 {
            get {
                return ResourceManager.GetString("String45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 串口通讯出现故障，无法断开串口连接！.
        /// </summary>
        internal static string String46 {
            get {
                return ResourceManager.GetString("String46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先连接仪器！.
        /// </summary>
        internal static string String47 {
            get {
                return ResourceManager.GetString("String47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回波强度[单位:count] (dB).
        /// </summary>
        internal static string String48 {
            get {
                return ResourceManager.GetString("String48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第.
        /// </summary>
        internal static string String49 {
            get {
                return ResourceManager.GetString("String49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解除暂停.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 层.
        /// </summary>
        internal static string String50 {
            get {
                return ResourceManager.GetString("String50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水流速剖面图[m/s](参考：大地).
        /// </summary>
        internal static string String51 {
            get {
                return ResourceManager.GetString("String51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 东.
        /// </summary>
        internal static string String52 {
            get {
                return ResourceManager.GetString("String52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 北.
        /// </summary>
        internal static string String53 {
            get {
                return ResourceManager.GetString("String53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 北分量剖面图[m/s](参考：大地).
        /// </summary>
        internal static string String54 {
            get {
                return ResourceManager.GetString("String54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 东分量剖面图[m/s](参考：大地).
        /// </summary>
        internal static string String55 {
            get {
                return ResourceManager.GetString("String55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相关性.
        /// </summary>
        internal static string String56 {
            get {
                return ResourceManager.GetString("String56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深度流速线（绿色）.
        /// </summary>
        internal static string String57 {
            get {
                return ResourceManager.GetString("String57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前点/总点数：.
        /// </summary>
        internal static string String58 {
            get {
                return ResourceManager.GetString("String58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前点：.
        /// </summary>
        internal static string String59 {
            get {
                return ResourceManager.GetString("String59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到文件.
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已记录点数：.
        /// </summary>
        internal static string String60 {
            get {
                return ResourceManager.GetString("String60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回放速度：.
        /// </summary>
        internal static string String61 {
            get {
                return ResourceManager.GetString("String61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动调节.
        /// </summary>
        internal static string String62 {
            get {
                return ResourceManager.GetString("String62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改变显示方向，请重新启动测量或回放。.
        /// </summary>
        internal static string String63 {
            get {
                return ResourceManager.GetString("String63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择文件路径!.
        /// </summary>
        internal static string String64 {
            get {
                return ResourceManager.GetString("String64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置文件已存在。用新文件覆盖？.
        /// </summary>
        internal static string String65 {
            get {
                return ResourceManager.GetString("String65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 矩形.
        /// </summary>
        internal static string String66 {
            get {
                return ResourceManager.GetString("String66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 河流测量停止.
        /// </summary>
        internal static string String67 {
            get {
                return ResourceManager.GetString("String67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 河流测量开始.
        /// </summary>
        internal static string String68 {
            get {
                return ResourceManager.GetString("String68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止测流.
        /// </summary>
        internal static string String69 {
            get {
                return ResourceManager.GetString("String69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请重新启动..
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始测流.
        /// </summary>
        internal static string String70 {
            get {
                return ResourceManager.GetString("String70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本次工程名：.
        /// </summary>
        internal static string String71 {
            get {
                return ResourceManager.GetString("String71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一步请选择《通讯》页，设置 ADCP串口 和 GPS串口。.
        /// </summary>
        internal static string String72 {
            get {
                return ResourceManager.GetString("String72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序执行错误! 请退出程序重新开始。.
        /// </summary>
        internal static string String73 {
            get {
                return ResourceManager.GetString("String73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工程测量：请检查各串行口情况；.
        /// </summary>
        internal static string String74 {
            get {
                return ResourceManager.GetString("String74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回放数据可能丢失，其他原始数据保留。.
        /// </summary>
        internal static string String75 {
            get {
                return ResourceManager.GetString("String75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入非负实数.
        /// </summary>
        internal static string String76 {
            get {
                return ResourceManager.GetString("String76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入非负整数.
        /// </summary>
        internal static string String77 {
            get {
                return ResourceManager.GetString("String77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每个文件存储样本数不能为0！.
        /// </summary>
        internal static string String78 {
            get {
                return ResourceManager.GetString("String78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 层厚不能为0！.
        /// </summary>
        internal static string String79 {
            get {
                return ResourceManager.GetString("String79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数输入不正确！.
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入-180到180间的实数！.
        /// </summary>
        internal static string String80 {
            get {
                return ResourceManager.GetString("String80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入0-100间的实数！.
        /// </summary>
        internal static string String81 {
            get {
                return ResourceManager.GetString("String81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入1-200间的整数！.
        /// </summary>
        internal static string String82 {
            get {
                return ResourceManager.GetString("String82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入0-10000间的整数！.
        /// </summary>
        internal static string String83 {
            get {
                return ResourceManager.GetString("String83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入0-10间的实数！.
        /// </summary>
        internal static string String84 {
            get {
                return ResourceManager.GetString("String84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入5-10000间的实数！.
        /// </summary>
        internal static string String85 {
            get {
                return ResourceManager.GetString("String85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String86 {
            get {
                return ResourceManager.GetString("String86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (空名称).
        /// </summary>
        internal static string String87 {
            get {
                return ResourceManager.GetString("String87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否停止当前回放，开始新的工程？.
        /// </summary>
        internal static string String88 {
            get {
                return ResourceManager.GetString("String88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否开始新的工程？.
        /// </summary>
        internal static string String89 {
            get {
                return ResourceManager.GetString("String89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大流速不能为0！.
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工程正在进行中，是否放弃当前工程，开始新的回放？.
        /// </summary>
        internal static string String90 {
            get {
                return ResourceManager.GetString("String90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件缺失，不能继续回放！.
        /// </summary>
        internal static string String91 {
            get {
                return ResourceManager.GetString("String91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流量信息.
        /// </summary>
        internal static string String92 {
            get {
                return ResourceManager.GetString("String92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顶部流量.
        /// </summary>
        internal static string String93 {
            get {
                return ResourceManager.GetString("String93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实测流量.
        /// </summary>
        internal static string String94 {
            get {
                return ResourceManager.GetString("String94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 底部流量.
        /// </summary>
        internal static string String95 {
            get {
                return ResourceManager.GetString("String95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左岸流量.
        /// </summary>
        internal static string String96 {
            get {
                return ResourceManager.GetString("String96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右岸流量.
        /// </summary>
        internal static string String97 {
            get {
                return ResourceManager.GetString("String97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总流量.
        /// </summary>
        internal static string String98 {
            get {
                return ResourceManager.GetString("String98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导航信息.
        /// </summary>
        internal static string String99 {
            get {
                return ResourceManager.GetString("String99", resourceCulture);
            }
        }
    }
}
