//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADCP {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADCP.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于... 的本地化字符串。
        /// </summary>
        internal static string str_About {
            get {
                return ResourceManager.GetString("str_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泛际测流大师软件 V4.0  2013-05 的本地化字符串。
        /// </summary>
        internal static string str_aboutText1 {
            get {
                return ResourceManager.GetString("str_aboutText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版权(C)2013-2018 上海泛际科学仪器有限公司 的本地化字符串。
        /// </summary>
        internal static string str_aboutText2 {
            get {
                return ResourceManager.GetString("str_aboutText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上海泛际科学仪器有限公司(Pan-Comm)是一家集研究开发、生产、销售及客户服务的高科技海洋仪器专业公司。公司集电子信息、计算机软件、仪器仪表等高端技术产业于一身，是“三高一无”科技企业。Pan-Comm并与国内外多家科研单位，高等院校和世界一流海洋仪器生产厂商合作，共同努力发展我国的海洋开发事业。 的本地化字符串。
        /// </summary>
        internal static string str_aboutText3 {
            get {
                return ResourceManager.GetString("str_aboutText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址：上海市漕河泾开发区松江高科园莘砖公路518弄11号楼701室 的本地化字符串。
        /// </summary>
        internal static string str_aboutText4 {
            get {
                return ResourceManager.GetString("str_aboutText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版权所有。 的本地化字符串。
        /// </summary>
        internal static string str_aboutText5 {
            get {
                return ResourceManager.GetString("str_aboutText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error! 线程已断，无法接受GPS数据。 的本地化字符串。
        /// </summary>
        internal static string str_errorGPS {
            get {
                return ResourceManager.GetString("str_errorGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助... 的本地化字符串。
        /// </summary>
        internal static string str_Help {
            get {
                return ResourceManager.GetString("str_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请参看 《RTI ADCP/DVL 用户手册》 及  的本地化字符串。
        /// </summary>
        internal static string str_HelpText1 {
            get {
                return ResourceManager.GetString("str_HelpText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 《测流大师（DP-Pro）软件应用指南》 的本地化字符串。
        /// </summary>
        internal static string str_HelpText2 {
            get {
                return ResourceManager.GetString("str_HelpText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示：DVL 测量： 的本地化字符串。
        /// </summary>
        internal static string str_noteDVL1 {
            get {
                return ResourceManager.GetString("str_noteDVL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您没有该功能的使用权限！ 的本地化字符串。
        /// </summary>
        internal static string str_noteDVL2 {
            get {
                return ResourceManager.GetString("str_noteDVL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示：您没有该功能的使用权限！ 的本地化字符串。
        /// </summary>
        internal static string str_noteRight1 {
            get {
                return ResourceManager.GetString("str_noteRight1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请联系上海泛际科学仪器有限公司 的本地化字符串。
        /// </summary>
        internal static string str_noteRight2 {
            get {
                return ResourceManager.GetString("str_noteRight2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示：波浪测量： 的本地化字符串。
        /// </summary>
        internal static string str_noteWave1 {
            get {
                return ResourceManager.GetString("str_noteWave1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话： +86 21 34060911 的本地化字符串。
        /// </summary>
        internal static string str_Tel {
            get {
                return ResourceManager.GetString("str_Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效结果: 的本地化字符串。
        /// </summary>
        internal static string str_unuse1 {
            get {
                return ResourceManager.GetString("str_unuse1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效结果: 的本地化字符串。
        /// </summary>
        internal static string str_use1 {
            get {
                return ResourceManager.GetString("str_use1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顶部流量: 的本地化字符串。
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯口名称不能为空 的本地化字符串。
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 船速 的本地化字符串。
        /// </summary>
        internal static string String100 {
            get {
                return ResourceManager.GetString("String100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 船向 的本地化字符串。
        /// </summary>
        internal static string String101 {
            get {
                return ResourceManager.GetString("String101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流速 的本地化字符串。
        /// </summary>
        internal static string String102 {
            get {
                return ResourceManager.GetString("String102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流向 的本地化字符串。
        /// </summary>
        internal static string String103 {
            get {
                return ResourceManager.GetString("String103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 航迹长度 的本地化字符串。
        /// </summary>
        internal static string String104 {
            get {
                return ResourceManager.GetString("String104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直线距离 的本地化字符串。
        /// </summary>
        internal static string String105 {
            get {
                return ResourceManager.GetString("String105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直线方向 的本地化字符串。
        /// </summary>
        internal static string String106 {
            get {
                return ResourceManager.GetString("String106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 河宽 的本地化字符串。
        /// </summary>
        internal static string String107 {
            get {
                return ResourceManager.GetString("String107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总面积 的本地化字符串。
        /// </summary>
        internal static string String108 {
            get {
                return ResourceManager.GetString("String108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平均流速 的本地化字符串。
        /// </summary>
        internal static string String109 {
            get {
                return ResourceManager.GetString("String109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口配置不正确！ 的本地化字符串。
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平均流向 的本地化字符串。
        /// </summary>
        internal static string String110 {
            get {
                return ResourceManager.GetString("String110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他信息 的本地化字符串。
        /// </summary>
        internal static string String111 {
            get {
                return ResourceManager.GetString("String111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        internal static string String112 {
            get {
                return ResourceManager.GetString("String112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测量时间 的本地化字符串。
        /// </summary>
        internal static string String113 {
            get {
                return ResourceManager.GetString("String113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测量总数 的本地化字符串。
        /// </summary>
        internal static string String114 {
            get {
                return ResourceManager.GetString("String114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前水深 的本地化字符串。
        /// </summary>
        internal static string String115 {
            get {
                return ResourceManager.GetString("String115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经度 的本地化字符串。
        /// </summary>
        internal static string String116 {
            get {
                return ResourceManager.GetString("String116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纬度 的本地化字符串。
        /// </summary>
        internal static string String117 {
            get {
                return ResourceManager.GetString("String117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艏向 的本地化字符串。
        /// </summary>
        internal static string String118 {
            get {
                return ResourceManager.GetString("String118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纵倾 的本地化字符串。
        /// </summary>
        internal static string String119 {
            get {
                return ResourceManager.GetString("String119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPS罗经串口配置不正确！ 的本地化字符串。
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 横摇 的本地化字符串。
        /// </summary>
        internal static string String120 {
            get {
                return ResourceManager.GetString("String120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 真北 的本地化字符串。
        /// </summary>
        internal static string String121 {
            get {
                return ResourceManager.GetString("String121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部显示 的本地化字符串。
        /// </summary>
        internal static string String122 {
            get {
                return ResourceManager.GetString("String122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部分显示/ 的本地化字符串。
        /// </summary>
        internal static string String123 {
            get {
                return ResourceManager.GetString("String123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浅水 的本地化字符串。
        /// </summary>
        internal static string String124 {
            get {
                return ResourceManager.GetString("String124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一般 的本地化字符串。
        /// </summary>
        internal static string String125 {
            get {
                return ResourceManager.GetString("String125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深水 的本地化字符串。
        /// </summary>
        internal static string String126 {
            get {
                return ResourceManager.GetString("String126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专家模式 的本地化字符串。
        /// </summary>
        internal static string String127 {
            get {
                return ResourceManager.GetString("String127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户模式 的本地化字符串。
        /// </summary>
        internal static string String128 {
            get {
                return ResourceManager.GetString("String128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 层数 的本地化字符串。
        /// </summary>
        internal static string String129 {
            get {
                return ResourceManager.GetString("String129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口冲突，请重设！ 的本地化字符串。
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先确保已安装Microsoft Office Excel 2007或以上版本！ 的本地化字符串。
        /// </summary>
        internal static string String130 {
            get {
                return ResourceManager.GetString("String130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先输入测站基本信息！ 的本地化字符串。
        /// </summary>
        internal static string String131 {
            get {
                return ResourceManager.GetString("String131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表B- 的本地化字符串。
        /// </summary>
        internal static string String132 {
            get {
                return ResourceManager.GetString("String132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 站声学多普勒流速仪测量测验记载表 的本地化字符串。
        /// </summary>
        internal static string String133 {
            get {
                return ResourceManager.GetString("String133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期: 的本地化字符串。
        /// </summary>
        internal static string String134 {
            get {
                return ResourceManager.GetString("String134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年 的本地化字符串。
        /// </summary>
        internal static string String135 {
            get {
                return ResourceManager.GetString("String135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月 的本地化字符串。
        /// </summary>
        internal static string String136 {
            get {
                return ResourceManager.GetString("String136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日 的本地化字符串。
        /// </summary>
        internal static string String137 {
            get {
                return ResourceManager.GetString("String137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天气： 的本地化字符串。
        /// </summary>
        internal static string String138 {
            get {
                return ResourceManager.GetString("String138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 风力风向： 的本地化字符串。
        /// </summary>
        internal static string String139 {
            get {
                return ResourceManager.GetString("String139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示：下一步请选择《测流控制》页，然后依次选择“连接仪器”和“开始测量”。 的本地化字符串。
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测量测次： 的本地化字符串。
        /// </summary>
        internal static string String140 {
            get {
                return ResourceManager.GetString("String140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测船： 的本地化字符串。
        /// </summary>
        internal static string String141 {
            get {
                return ResourceManager.GetString("String141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算机名： 的本地化字符串。
        /// </summary>
        internal static string String142 {
            get {
                return ResourceManager.GetString("String142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间： 的本地化字符串。
        /// </summary>
        internal static string String143 {
            get {
                return ResourceManager.GetString("String143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束时间： 的本地化字符串。
        /// </summary>
        internal static string String144 {
            get {
                return ResourceManager.GetString("String144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平均时间： 的本地化字符串。
        /// </summary>
        internal static string String145 {
            get {
                return ResourceManager.GetString("String145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测速仪型号： 的本地化字符串。
        /// </summary>
        internal static string String146 {
            get {
                return ResourceManager.GetString("String146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 固件版本： 的本地化字符串。
        /// </summary>
        internal static string String147 {
            get {
                return ResourceManager.GetString("String147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件版本： 的本地化字符串。
        /// </summary>
        internal static string String148 {
            get {
                return ResourceManager.GetString("String148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据文件路径： 的本地化字符串。
        /// </summary>
        internal static string String149 {
            get {
                return ResourceManager.GetString("String149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目前处于回放模式，请先切换至跟踪显示模式，再配置！ 的本地化字符串。
        /// </summary>
        internal static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置文件名称：Config.cfg 的本地化字符串。
        /// </summary>
        internal static string String150 {
            get {
                return ResourceManager.GetString("String150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPS型号： 的本地化字符串。
        /// </summary>
        internal static string String151 {
            get {
                return ResourceManager.GetString("String151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 罗经型号： 的本地化字符串。
        /// </summary>
        internal static string String152 {
            get {
                return ResourceManager.GetString("String152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测深仪型号： 的本地化字符串。
        /// </summary>
        internal static string String153 {
            get {
                return ResourceManager.GetString("String153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 探头入水深: 的本地化字符串。
        /// </summary>
        internal static string String154 {
            get {
                return ResourceManager.GetString("String154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置的盲区： 的本地化字符串。
        /// </summary>
        internal static string String155 {
            get {
                return ResourceManager.GetString("String155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深度单元尺寸: 的本地化字符串。
        /// </summary>
        internal static string String156 {
            get {
                return ResourceManager.GetString("String156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深度单元数： 的本地化字符串。
        /// </summary>
        internal static string String157 {
            get {
                return ResourceManager.GetString("String157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 含盐度： 的本地化字符串。
        /// </summary>
        internal static string String158 {
            get {
                return ResourceManager.GetString("String158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水跟踪脉冲数： 的本地化字符串。
        /// </summary>
        internal static string String159 {
            get {
                return ResourceManager.GetString("String159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口通讯出现故障！ 的本地化字符串。
        /// </summary>
        internal static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 底跟踪脉冲数： 的本地化字符串。
        /// </summary>
        internal static string String160 {
            get {
                return ResourceManager.GetString("String160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 幂指数b: 的本地化字符串。
        /// </summary>
        internal static string String161 {
            get {
                return ResourceManager.GetString("String161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测回 的本地化字符串。
        /// </summary>
        internal static string String162 {
            get {
                return ResourceManager.GetString("String162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 航向 的本地化字符串。
        /// </summary>
        internal static string String163 {
            get {
                return ResourceManager.GetString("String163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水边距离 的本地化字符串。
        /// </summary>
        internal static string String164 {
            get {
                return ResourceManager.GetString("String164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据文件名 的本地化字符串。
        /// </summary>
        internal static string String165 {
            get {
                return ResourceManager.GetString("String165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 半测回流量 的本地化字符串。
        /// </summary>
        internal static string String166 {
            get {
                return ResourceManager.GetString("String166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测回平均流量 的本地化字符串。
        /// </summary>
        internal static string String167 {
            get {
                return ResourceManager.GetString("String167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string String168 {
            get {
                return ResourceManager.GetString("String168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右岸-左岸 的本地化字符串。
        /// </summary>
        internal static string String169 {
            get {
                return ResourceManager.GetString("String169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先连接串口！ 的本地化字符串。
        /// </summary>
        internal static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左岸-右岸 的本地化字符串。
        /// </summary>
        internal static string String170 {
            get {
                return ResourceManager.GetString("String170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测    验    结    果 的本地化字符串。
        /// </summary>
        internal static string String171 {
            get {
                return ResourceManager.GetString("String171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测验项目 的本地化字符串。
        /// </summary>
        internal static string String172 {
            get {
                return ResourceManager.GetString("String172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测回 的本地化字符串。
        /// </summary>
        internal static string String173 {
            get {
                return ResourceManager.GetString("String173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测次平均 的本地化字符串。
        /// </summary>
        internal static string String174 {
            get {
                return ResourceManager.GetString("String174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 往测 的本地化字符串。
        /// </summary>
        internal static string String175 {
            get {
                return ResourceManager.GetString("String175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返测 的本地化字符串。
        /// </summary>
        internal static string String176 {
            get {
                return ResourceManager.GetString("String176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断面流量 的本地化字符串。
        /// </summary>
        internal static string String177 {
            get {
                return ResourceManager.GetString("String177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断面面积 的本地化字符串。
        /// </summary>
        internal static string String178 {
            get {
                return ResourceManager.GetString("String178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平均流速 的本地化字符串。
        /// </summary>
        internal static string String179 {
            get {
                return ResourceManager.GetString("String179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统正在进行工程测量，是否要保存工程文件？ 的本地化字符串。
        /// </summary>
        internal static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大流速 的本地化字符串。
        /// </summary>
        internal static string String180 {
            get {
                return ResourceManager.GetString("String180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平均水深 的本地化字符串。
        /// </summary>
        internal static string String181 {
            get {
                return ResourceManager.GetString("String181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大水深 的本地化字符串。
        /// </summary>
        internal static string String182 {
            get {
                return ResourceManager.GetString("String182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水面宽 的本地化字符串。
        /// </summary>
        internal static string String183 {
            get {
                return ResourceManager.GetString("String183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始水位： 的本地化字符串。
        /// </summary>
        internal static string String184 {
            get {
                return ResourceManager.GetString("String184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束水位： 的本地化字符串。
        /// </summary>
        internal static string String185 {
            get {
                return ResourceManager.GetString("String185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平均水位： 的本地化字符串。
        /// </summary>
        internal static string String186 {
            get {
                return ResourceManager.GetString("String186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相应水位： 的本地化字符串。
        /// </summary>
        internal static string String187 {
            get {
                return ResourceManager.GetString("String187", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作记录： 的本地化字符串。
        /// </summary>
        internal static string String188 {
            get {
                return ResourceManager.GetString("String188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现场审查： 的本地化字符串。
        /// </summary>
        internal static string String189 {
            get {
                return ResourceManager.GetString("String189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审定： 的本地化字符串。
        /// </summary>
        internal static string String190 {
            get {
                return ResourceManager.GetString("String190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 楷体 的本地化字符串。
        /// </summary>
        internal static string String191 {
            get {
                return ResourceManager.GetString("String191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存: 的本地化字符串。
        /// </summary>
        internal static string String192 {
            get {
                return ResourceManager.GetString("String192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户模式：建议一般用户使用！ 的本地化字符串。
        /// </summary>
        internal static string String193 {
            get {
                return ResourceManager.GetString("String193", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专家模式：根据详细的命令设置配置！ 的本地化字符串。
        /// </summary>
        internal static string String194 {
            get {
                return ResourceManager.GetString("String194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当底跟踪的信噪比小于设置的门限值时，认为该值不好。默认门限值浅水为15，深水为5 的本地化字符串。
        /// </summary>
        internal static string String195 {
            get {
                return ResourceManager.GetString("String195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当底跟踪的相关性值小于设置的门限值时，认为该值不好，且该值不用于计算平均值。默认门限值为0.9 的本地化字符串。
        /// </summary>
        internal static string String196 {
            get {
                return ResourceManager.GetString("String196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当水剖面的相关性小于设置的门限值是，认为该值不好，且该值不用于bin平均。默认门限值为0.4 的本地化字符串。
        /// </summary>
        internal static string String197 {
            get {
                return ResourceManager.GetString("String197", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测流地理坐标良好率是指在该单元层中的发射的呯数与实际可用的呯数的比值 的本地化字符串。
        /// </summary>
        internal static string String198 {
            get {
                return ResourceManager.GetString("String198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测流波束坐标良好率 的本地化字符串。
        /// </summary>
        internal static string String199 {
            get {
                return ResourceManager.GetString("String199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 底部流量: 的本地化字符串。
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败，回放所必需的文件丢失！ 的本地化字符串。
        /// </summary>
        internal static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地球坐标系下的流速 的本地化字符串。
        /// </summary>
        internal static string String200 {
            get {
                return ResourceManager.GetString("String200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仪器坐标系下的流速 的本地化字符串。
        /// </summary>
        internal static string String201 {
            get {
                return ResourceManager.GetString("String201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波束方向上的流速 的本地化字符串。
        /// </summary>
        internal static string String202 {
            get {
                return ResourceManager.GetString("String202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地球坐标系下的底跟踪速度 的本地化字符串。
        /// </summary>
        internal static string String203 {
            get {
                return ResourceManager.GetString("String203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仪器坐标系下的底跟踪速度 的本地化字符串。
        /// </summary>
        internal static string String204 {
            get {
                return ResourceManager.GetString("String204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波束方向的底跟踪速度 的本地化字符串。
        /// </summary>
        internal static string String205 {
            get {
                return ResourceManager.GetString("String205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地球坐标系的水剖面ping的良好率 的本地化字符串。
        /// </summary>
        internal static string String206 {
            get {
                return ResourceManager.GetString("String206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波束方向上的水剖面ping的良好率 的本地化字符串。
        /// </summary>
        internal static string String207 {
            get {
                return ResourceManager.GetString("String207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地球坐标系下的底跟踪ping的良好率 的本地化字符串。
        /// </summary>
        internal static string String208 {
            get {
                return ResourceManager.GetString("String208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仪器坐标系下的底跟踪ping的良好率 的本地化字符串。
        /// </summary>
        internal static string String209 {
            get {
                return ResourceManager.GetString("String209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工程名： 的本地化字符串。
        /// </summary>
        internal static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波束方向上的底跟踪ping的良好率 的本地化字符串。
        /// </summary>
        internal static string String210 {
            get {
                return ResourceManager.GetString("String210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水剖面相关性，默认的相关性阈值为0.4。当某个单元层的相关性值小于设定的阈值，则认为该数据不可用，予以剔除。 的本地化字符串。
        /// </summary>
        internal static string String211 {
            get {
                return ResourceManager.GetString("String211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 底跟踪相关性，默认的底跟踪相关性阈值为0.9。当某一ping的相关性小于设定的阈值，则认为该数据不可用，予以剔除。 的本地化字符串。
        /// </summary>
        internal static string String212 {
            get {
                return ResourceManager.GetString("String212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水剖面回波强度 的本地化字符串。
        /// </summary>
        internal static string String213 {
            get {
                return ResourceManager.GetString("String213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 底跟踪回波强度 的本地化字符串。
        /// </summary>
        internal static string String214 {
            get {
                return ResourceManager.GetString("String214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (m/s) 的本地化字符串。
        /// </summary>
        internal static string String215 {
            get {
                return ResourceManager.GetString("String215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (度) 的本地化字符串。
        /// </summary>
        internal static string String216 {
            get {
                return ResourceManager.GetString("String216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该页面用于配置流量测量参数。 的本地化字符串。
        /// </summary>
        internal static string String217 {
            get {
                return ResourceManager.GetString("String217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当用户设置完成所有配置参数后，请点击工具栏上的“开始”按钮（或点击快捷键“F5”），启动流量测量。 的本地化字符串。
        /// </summary>
        internal static string String218 {
            get {
                return ResourceManager.GetString("String218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户可根据实际情况修改流量测量参数。 的本地化字符串。
        /// </summary>
        internal static string String219 {
            get {
                return ResourceManager.GetString("String219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间： 的本地化字符串。
        /// </summary>
        internal static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流速剖面图 - 参考: 的本地化字符串。
        /// </summary>
        internal static string String220 {
            get {
                return ResourceManager.GetString("String220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三角形 (斜坡) 的本地化字符串。
        /// </summary>
        internal static string String221 {
            get {
                return ResourceManager.GetString("String221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 矩形 (垂直) 的本地化字符串。
        /// </summary>
        internal static string String222 {
            get {
                return ResourceManager.GetString("String222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义 的本地化字符串。
        /// </summary>
        internal static string String223 {
            get {
                return ResourceManager.GetString("String223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常数 的本地化字符串。
        /// </summary>
        internal static string String224 {
            get {
                return ResourceManager.GetString("String224", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三点外延 的本地化字符串。
        /// </summary>
        internal static string String225 {
            get {
                return ResourceManager.GetString("String225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左岸 的本地化字符串。
        /// </summary>
        internal static string String226 {
            get {
                return ResourceManager.GetString("String226", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右岸 的本地化字符串。
        /// </summary>
        internal static string String227 {
            get {
                return ResourceManager.GetString("String227", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件计算 的本地化字符串。
        /// </summary>
        internal static string String228 {
            get {
                return ResourceManager.GetString("String228", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仪器获取 的本地化字符串。
        /// </summary>
        internal static string String229 {
            get {
                return ResourceManager.GetString("String229", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件路径： 的本地化字符串。
        /// </summary>
        internal static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内置罗盘 的本地化字符串。
        /// </summary>
        internal static string String230 {
            get {
                return ResourceManager.GetString("String230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外接罗盘 的本地化字符串。
        /// </summary>
        internal static string String231 {
            get {
                return ResourceManager.GetString("String231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 底跟踪 的本地化字符串。
        /// </summary>
        internal static string String232 {
            get {
                return ResourceManager.GetString("String232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无参考 的本地化字符串。
        /// </summary>
        internal static string String233 {
            get {
                return ResourceManager.GetString("String233", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户模式 的本地化字符串。
        /// </summary>
        internal static string String234 {
            get {
                return ResourceManager.GetString("String234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专家模式 的本地化字符串。
        /// </summary>
        internal static string String235 {
            get {
                return ResourceManager.GetString("String235", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公制 的本地化字符串。
        /// </summary>
        internal static string String236 {
            get {
                return ResourceManager.GetString("String236", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英制 的本地化字符串。
        /// </summary>
        internal static string String237 {
            get {
                return ResourceManager.GetString("String237", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水深 的本地化字符串。
        /// </summary>
        internal static string String238 {
            get {
                return ResourceManager.GetString("String238", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测量 的本地化字符串。
        /// </summary>
        internal static string String239 {
            get {
                return ResourceManager.GetString("String239", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否放弃当前回放，开始新的项目回放？ 的本地化字符串。
        /// </summary>
        internal static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回放 的本地化字符串。
        /// </summary>
        internal static string String240 {
            get {
                return ResourceManager.GetString("String240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        internal static string String241 {
            get {
                return ResourceManager.GetString("String241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        internal static string String242 {
            get {
                return ResourceManager.GetString("String242", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 美国亚奇科技公司 的本地化字符串。
        /// </summary>
        internal static string String243 {
            get {
                return ResourceManager.GetString("String243", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上海泛际科学仪器有限公司 的本地化字符串。
        /// </summary>
        internal static string String244 {
            get {
                return ResourceManager.GetString("String244", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该程序正在运行，请勿重复运行！ 的本地化字符串。
        /// </summary>
        internal static string String245 {
            get {
                return ResourceManager.GetString("String245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户手册 的本地化字符串。
        /// </summary>
        internal static string String246 {
            get {
                return ResourceManager.GetString("String246", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RTI网站 的本地化字符串。
        /// </summary>
        internal static string String247 {
            get {
                return ResourceManager.GetString("String247", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泛际网站 的本地化字符串。
        /// </summary>
        internal static string String248 {
            get {
                return ResourceManager.GetString("String248", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泛际测流大师软件 的本地化字符串。
        /// </summary>
        internal static string String249 {
            get {
                return ResourceManager.GetString("String249", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法打开原始数据，请检查原始数据文件是否有效！ 的本地化字符串。
        /// </summary>
        internal static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本: 的本地化字符串。
        /// </summary>
        internal static string String250 {
            get {
                return ResourceManager.GetString("String250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上海泛际科学仪器有限公司 的本地化字符串。
        /// </summary>
        internal static string String251 {
            get {
                return ResourceManager.GetString("String251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版权所有@ 的本地化字符串。
        /// </summary>
        internal static string String252 {
            get {
                return ResourceManager.GetString("String252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平均值 的本地化字符串。
        /// </summary>
        internal static string String253 {
            get {
                return ResourceManager.GetString("String253", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准差 的本地化字符串。
        /// </summary>
        internal static string String254 {
            get {
                return ResourceManager.GetString("String254", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 误差 的本地化字符串。
        /// </summary>
        internal static string String255 {
            get {
                return ResourceManager.GetString("String255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始岸边测量，请点击这里！（或按快捷键“F5”） 的本地化字符串。
        /// </summary>
        internal static string String256 {
            get {
                return ResourceManager.GetString("String256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始走航测量，请点击这里！（或按快捷键“F5”） 的本地化字符串。
        /// </summary>
        internal static string String257 {
            get {
                return ResourceManager.GetString("String257", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始发射呯，请点击这里！（或按快捷键“F5”） 的本地化字符串。
        /// </summary>
        internal static string String258 {
            get {
                return ResourceManager.GetString("String258", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止发射呯，请点击这里！（或按快捷键“F6”） 的本地化字符串。
        /// </summary>
        internal static string String259 {
            get {
                return ResourceManager.GetString("String259", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 载入回放数据错误，请检查文件格式是否正确！ 的本地化字符串。
        /// </summary>
        internal static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名 的本地化字符串。
        /// </summary>
        internal static string String260 {
            get {
                return ResourceManager.GetString("String260", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始日期 的本地化字符串。
        /// </summary>
        internal static string String261 {
            get {
                return ResourceManager.GetString("String261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始时间 的本地化字符串。
        /// </summary>
        internal static string String262 {
            get {
                return ResourceManager.GetString("String262", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在发射呯 的本地化字符串。
        /// </summary>
        internal static string String263 {
            get {
                return ResourceManager.GetString("String263", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在测量起始岸 的本地化字符串。
        /// </summary>
        internal static string String264 {
            get {
                return ResourceManager.GetString("String264", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在走航 的本地化字符串。
        /// </summary>
        internal static string String265 {
            get {
                return ResourceManager.GetString("String265", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在测量结束岸 的本地化字符串。
        /// </summary>
        internal static string String266 {
            get {
                return ResourceManager.GetString("String266", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止发射呯 的本地化字符串。
        /// </summary>
        internal static string String267 {
            get {
                return ResourceManager.GetString("String267", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据组号 的本地化字符串。
        /// </summary>
        internal static string String268 {
            get {
                return ResourceManager.GetString("String268", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        internal static string String269 {
            get {
                return ResourceManager.GetString("String269", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回放文件终端，请退出或改变回放起点。 的本地化字符串。
        /// </summary>
        internal static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (度) 的本地化字符串。
        /// </summary>
        internal static string String270 {
            get {
                return ResourceManager.GetString("String270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 船速/流速 的本地化字符串。
        /// </summary>
        internal static string String271 {
            get {
                return ResourceManager.GetString("String271", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 航迹距离 的本地化字符串。
        /// </summary>
        internal static string String272 {
            get {
                return ResourceManager.GetString("String272", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一个 的本地化字符串。
        /// </summary>
        internal static string String273 {
            get {
                return ResourceManager.GetString("String273", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示汇总信息 的本地化字符串。
        /// </summary>
        internal static string String274 {
            get {
                return ResourceManager.GetString("String274", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        internal static string String275 {
            get {
                return ResourceManager.GetString("String275", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        internal static string String276 {
            get {
                return ResourceManager.GetString("String276", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始测量 的本地化字符串。
        /// </summary>
        internal static string String277 {
            get {
                return ResourceManager.GetString("String277", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始岸边 的本地化字符串。
        /// </summary>
        internal static string String278 {
            get {
                return ResourceManager.GetString("String278", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 走航 的本地化字符串。
        /// </summary>
        internal static string String279 {
            get {
                return ResourceManager.GetString("String279", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未创建工程... ... 的本地化字符串。
        /// </summary>
        internal static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束岸边 的本地化字符串。
        /// </summary>
        internal static string String280 {
            get {
                return ResourceManager.GetString("String280", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束测量 的本地化字符串。
        /// </summary>
        internal static string String281 {
            get {
                return ResourceManager.GetString("String281", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string String282 {
            get {
                return ResourceManager.GetString("String282", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先查看测量模式(第四步：系统设置)！ 的本地化字符串。
        /// </summary>
        internal static string String283 {
            get {
                return ResourceManager.GetString("String283", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上海泛际 的本地化字符串。
        /// </summary>
        internal static string String284 {
            get {
                return ResourceManager.GetString("String284", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到下一个可读文件！ 的本地化字符串。
        /// </summary>
        internal static string String285 {
            get {
                return ResourceManager.GetString("String285", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口被占用 的本地化字符串。
        /// </summary>
        internal static string String286 {
            get {
                return ResourceManager.GetString("String286", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 极浅水 的本地化字符串。
        /// </summary>
        internal static string String287 {
            get {
                return ResourceManager.GetString("String287", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统罗盘未工作。 的本地化字符串。
        /// </summary>
        internal static string String288 {
            get {
                return ResourceManager.GetString("String288", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总大小： 的本地化字符串。
        /// </summary>
        internal static string String289 {
            get {
                return ResourceManager.GetString("String289", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未接受任何数据... ... 的本地化字符串。
        /// </summary>
        internal static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已用空间： 的本地化字符串。
        /// </summary>
        internal static string String290 {
            get {
                return ResourceManager.GetString("String290", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到SD卡。 的本地化字符串。
        /// </summary>
        internal static string String291 {
            get {
                return ResourceManager.GetString("String291", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统电量为： 的本地化字符串。
        /// </summary>
        internal static string String292 {
            get {
                return ResourceManager.GetString("String292", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水温为： 的本地化字符串。
        /// </summary>
        internal static string String293 {
            get {
                return ResourceManager.GetString("String293", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未检测到温度传感器。 的本地化字符串。
        /// </summary>
        internal static string String294 {
            get {
                return ResourceManager.GetString("String294", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统测试 的本地化字符串。
        /// </summary>
        internal static string String295 {
            get {
                return ResourceManager.GetString("String295", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯故障 的本地化字符串。
        /// </summary>
        internal static string String296 {
            get {
                return ResourceManager.GetString("String296", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请检查ADCP通讯线路或电源供电是否正常 的本地化字符串。
        /// </summary>
        internal static string String297 {
            get {
                return ResourceManager.GetString("String297", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请检查GPS通讯线路或电源供电是否正常 的本地化字符串。
        /// </summary>
        internal static string String298 {
            get {
                return ResourceManager.GetString("String298", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在下载... 的本地化字符串。
        /// </summary>
        internal static string String299 {
            get {
                return ResourceManager.GetString("String299", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实测流量: 的本地化字符串。
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无GPS数据... ... 的本地化字符串。
        /// </summary>
        internal static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载完成 的本地化字符串。
        /// </summary>
        internal static string String300 {
            get {
                return ResourceManager.GetString("String300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载失败 的本地化字符串。
        /// </summary>
        internal static string String301 {
            get {
                return ResourceManager.GetString("String301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送DSDIR命令失败 的本地化字符串。
        /// </summary>
        internal static string String302 {
            get {
                return ResourceManager.GetString("String302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网址： 的本地化字符串。
        /// </summary>
        internal static string String303 {
            get {
                return ResourceManager.GetString("String303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到软件狗！ 的本地化字符串。
        /// </summary>
        internal static string String304 {
            get {
                return ResourceManager.GetString("String304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采用默认配置 的本地化字符串。
        /// </summary>
        internal static string String305 {
            get {
                return ResourceManager.GetString("String305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始数据采集，请点击这里！（或按快捷键“F5”） 的本地化字符串。
        /// </summary>
        internal static string String306 {
            get {
                return ResourceManager.GetString("String306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止数据采集，请点击这里！（或按快捷键“F6”） 的本地化字符串。
        /// </summary>
        internal static string String307 {
            get {
                return ResourceManager.GetString("String307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在数据采集 的本地化字符串。
        /// </summary>
        internal static string String308 {
            get {
                return ResourceManager.GetString("String308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止数据采集 的本地化字符串。
        /// </summary>
        internal static string String309 {
            get {
                return ResourceManager.GetString("String309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接仪器 的本地化字符串。
        /// </summary>
        internal static string String31 {
            get {
                return ResourceManager.GetString("String31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流量报表输出完成！ 的本地化字符串。
        /// </summary>
        internal static string String310 {
            get {
                return ResourceManager.GetString("String310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流量报表输出失败！ 的本地化字符串。
        /// </summary>
        internal static string String311 {
            get {
                return ResourceManager.GetString("String311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流量报表输出失败，缺少流量数据！ 的本地化字符串。
        /// </summary>
        internal static string String312 {
            get {
                return ResourceManager.GetString("String312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 航迹图 的本地化字符串。
        /// </summary>
        internal static string String313 {
            get {
                return ResourceManager.GetString("String313", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 船速参考 的本地化字符串。
        /// </summary>
        internal static string String314 {
            get {
                return ResourceManager.GetString("String314", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始发射 的本地化字符串。
        /// </summary>
        internal static string String32 {
            get {
                return ResourceManager.GetString("String32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 幂函数 的本地化字符串。
        /// </summary>
        internal static string String33 {
            get {
                return ResourceManager.GetString("String33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三角形 的本地化字符串。
        /// </summary>
        internal static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统正在进行工程回放，是否要结束回放？ 的本地化字符串。
        /// </summary>
        internal static string String35 {
            get {
                return ResourceManager.GetString("String35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要退出测量？ 的本地化字符串。
        /// </summary>
        internal static string String36 {
            get {
                return ResourceManager.GetString("String36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选用GPS罗经时必须同时选定GPS！ 的本地化字符串。
        /// </summary>
        internal static string String37 {
            get {
                return ResourceManager.GetString("String37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改失败，输入配置参数据有误，请检查！ 的本地化字符串。
        /// </summary>
        internal static string String38 {
            get {
                return ResourceManager.GetString("String38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置文件丢失，请重新选择。 的本地化字符串。
        /// </summary>
        internal static string String39 {
            get {
                return ResourceManager.GetString("String39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 岸边流量: 的本地化字符串。
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断开仪器 的本地化字符串。
        /// </summary>
        internal static string String40 {
            get {
                return ResourceManager.GetString("String40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有创建工程，请先点击“新建工程”按钮以创建系的工程。 的本地化字符串。
        /// </summary>
        internal static string String41 {
            get {
                return ResourceManager.GetString("String41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPS连接失败！ 的本地化字符串。
        /// </summary>
        internal static string String42 {
            get {
                return ResourceManager.GetString("String42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在接受数据... ... 的本地化字符串。
        /// </summary>
        internal static string String43 {
            get {
                return ResourceManager.GetString("String43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停发射 的本地化字符串。
        /// </summary>
        internal static string String44 {
            get {
                return ResourceManager.GetString("String44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口通讯出现故障,无法连接仪器串口！ 的本地化字符串。
        /// </summary>
        internal static string String45 {
            get {
                return ResourceManager.GetString("String45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口通讯出现故障，无法断开串口连接！ 的本地化字符串。
        /// </summary>
        internal static string String46 {
            get {
                return ResourceManager.GetString("String46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先连接仪器！ 的本地化字符串。
        /// </summary>
        internal static string String47 {
            get {
                return ResourceManager.GetString("String47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回波强度[单位:count] (20 counts≈1 db) 的本地化字符串。
        /// </summary>
        internal static string String48 {
            get {
                return ResourceManager.GetString("String48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 的本地化字符串。
        /// </summary>
        internal static string String49 {
            get {
                return ResourceManager.GetString("String49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解除暂停 的本地化字符串。
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 层 的本地化字符串。
        /// </summary>
        internal static string String50 {
            get {
                return ResourceManager.GetString("String50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水流速剖面图[m/s](参考：大地) 的本地化字符串。
        /// </summary>
        internal static string String51 {
            get {
                return ResourceManager.GetString("String51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 东 的本地化字符串。
        /// </summary>
        internal static string String52 {
            get {
                return ResourceManager.GetString("String52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 北 的本地化字符串。
        /// </summary>
        internal static string String53 {
            get {
                return ResourceManager.GetString("String53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 北分量剖面图[m/s](参考：大地) 的本地化字符串。
        /// </summary>
        internal static string String54 {
            get {
                return ResourceManager.GetString("String54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 东分量剖面图[m/s](参考：大地) 的本地化字符串。
        /// </summary>
        internal static string String55 {
            get {
                return ResourceManager.GetString("String55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相关性 的本地化字符串。
        /// </summary>
        internal static string String56 {
            get {
                return ResourceManager.GetString("String56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深度流速线（绿色） 的本地化字符串。
        /// </summary>
        internal static string String57 {
            get {
                return ResourceManager.GetString("String57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前点/总点数： 的本地化字符串。
        /// </summary>
        internal static string String58 {
            get {
                return ResourceManager.GetString("String58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前点： 的本地化字符串。
        /// </summary>
        internal static string String59 {
            get {
                return ResourceManager.GetString("String59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到文件 的本地化字符串。
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已记录点数： 的本地化字符串。
        /// </summary>
        internal static string String60 {
            get {
                return ResourceManager.GetString("String60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回放速度： 的本地化字符串。
        /// </summary>
        internal static string String61 {
            get {
                return ResourceManager.GetString("String61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动调节 的本地化字符串。
        /// </summary>
        internal static string String62 {
            get {
                return ResourceManager.GetString("String62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改变显示方向，请重新启动测量或回放。 的本地化字符串。
        /// </summary>
        internal static string String63 {
            get {
                return ResourceManager.GetString("String63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择文件路径! 的本地化字符串。
        /// </summary>
        internal static string String64 {
            get {
                return ResourceManager.GetString("String64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置文件已存在。用新文件覆盖？ 的本地化字符串。
        /// </summary>
        internal static string String65 {
            get {
                return ResourceManager.GetString("String65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 矩形 的本地化字符串。
        /// </summary>
        internal static string String66 {
            get {
                return ResourceManager.GetString("String66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 河流测量停止 的本地化字符串。
        /// </summary>
        internal static string String67 {
            get {
                return ResourceManager.GetString("String67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 河流测量开始 的本地化字符串。
        /// </summary>
        internal static string String68 {
            get {
                return ResourceManager.GetString("String68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止测流 的本地化字符串。
        /// </summary>
        internal static string String69 {
            get {
                return ResourceManager.GetString("String69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请重新启动. 的本地化字符串。
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始测流 的本地化字符串。
        /// </summary>
        internal static string String70 {
            get {
                return ResourceManager.GetString("String70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本次工程名： 的本地化字符串。
        /// </summary>
        internal static string String71 {
            get {
                return ResourceManager.GetString("String71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一步请选择《通讯》页，设置 ADCP串口 和 GPS串口。 的本地化字符串。
        /// </summary>
        internal static string String72 {
            get {
                return ResourceManager.GetString("String72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序执行错误! 请退出程序重新开始。 的本地化字符串。
        /// </summary>
        internal static string String73 {
            get {
                return ResourceManager.GetString("String73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工程测量：请检查各串行口情况； 的本地化字符串。
        /// </summary>
        internal static string String74 {
            get {
                return ResourceManager.GetString("String74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回放数据可能丢失，其他原始数据保留。 的本地化字符串。
        /// </summary>
        internal static string String75 {
            get {
                return ResourceManager.GetString("String75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入非负实数 的本地化字符串。
        /// </summary>
        internal static string String76 {
            get {
                return ResourceManager.GetString("String76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入非负整数 的本地化字符串。
        /// </summary>
        internal static string String77 {
            get {
                return ResourceManager.GetString("String77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每个文件存储样本数不能为0！ 的本地化字符串。
        /// </summary>
        internal static string String78 {
            get {
                return ResourceManager.GetString("String78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 层厚不能为0！ 的本地化字符串。
        /// </summary>
        internal static string String79 {
            get {
                return ResourceManager.GetString("String79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数输入不正确！ 的本地化字符串。
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入-180到180间的实数！ 的本地化字符串。
        /// </summary>
        internal static string String80 {
            get {
                return ResourceManager.GetString("String80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入0-100间的实数！ 的本地化字符串。
        /// </summary>
        internal static string String81 {
            get {
                return ResourceManager.GetString("String81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入1-200间的整数！ 的本地化字符串。
        /// </summary>
        internal static string String82 {
            get {
                return ResourceManager.GetString("String82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入0-10000间的整数！ 的本地化字符串。
        /// </summary>
        internal static string String83 {
            get {
                return ResourceManager.GetString("String83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入0-10间的实数！ 的本地化字符串。
        /// </summary>
        internal static string String84 {
            get {
                return ResourceManager.GetString("String84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入5-10000间的实数！ 的本地化字符串。
        /// </summary>
        internal static string String85 {
            get {
                return ResourceManager.GetString("String85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string String86 {
            get {
                return ResourceManager.GetString("String86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (空名称) 的本地化字符串。
        /// </summary>
        internal static string String87 {
            get {
                return ResourceManager.GetString("String87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否停止当前回放，开始新的工程？ 的本地化字符串。
        /// </summary>
        internal static string String88 {
            get {
                return ResourceManager.GetString("String88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否开始新的工程？ 的本地化字符串。
        /// </summary>
        internal static string String89 {
            get {
                return ResourceManager.GetString("String89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大流速不能为0！ 的本地化字符串。
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工程正在进行中，是否放弃当前工程，开始新的回放？ 的本地化字符串。
        /// </summary>
        internal static string String90 {
            get {
                return ResourceManager.GetString("String90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件缺失，不能继续回放！ 的本地化字符串。
        /// </summary>
        internal static string String91 {
            get {
                return ResourceManager.GetString("String91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流量信息 的本地化字符串。
        /// </summary>
        internal static string String92 {
            get {
                return ResourceManager.GetString("String92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顶部流量 的本地化字符串。
        /// </summary>
        internal static string String93 {
            get {
                return ResourceManager.GetString("String93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实测流量 的本地化字符串。
        /// </summary>
        internal static string String94 {
            get {
                return ResourceManager.GetString("String94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 底部流量 的本地化字符串。
        /// </summary>
        internal static string String95 {
            get {
                return ResourceManager.GetString("String95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左岸流量 的本地化字符串。
        /// </summary>
        internal static string String96 {
            get {
                return ResourceManager.GetString("String96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右岸流量 的本地化字符串。
        /// </summary>
        internal static string String97 {
            get {
                return ResourceManager.GetString("String97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总流量 的本地化字符串。
        /// </summary>
        internal static string String98 {
            get {
                return ResourceManager.GetString("String98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导航信息 的本地化字符串。
        /// </summary>
        internal static string String99 {
            get {
                return ResourceManager.GetString("String99", resourceCulture);
            }
        }
    }
}
